### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'loop'

### ISSUE THREAD

**Issue by wanghaisheng** [YusukeIwaki/playwright-python-remote#11]
$ PLAYWRIGHT_WS_URL=wss://playwrightserver.herokuapp.com/ws python ex.py
Traceback (most recent call last):
  File "ex.py", line 4, in <module>
    with playwright_browser('chromium') as browser:
  File "D:\Program Files\anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\Download\audio-visual\saas\deploy\playwright-python-playWithWebSocket\with_playwright_browser.py", line 11, in playwright_browser
    with sync_playwright_remote(ws_endpoint) as playwright:
  File "D:\Download\audio-visual\saas\deploy\playwright-python-playWithWebSocket\playwright_remote_context_manager.py", line 41, in __enter__
    self._connection = Connection(
TypeError: __init__() missing 1 required positional argument: 'loop'

**Comment by YusukeIwaki** [comment]
It seems you are using older version of example code in https://github.com/YusukeIwaki/playwright-python-playWithWebSocket

It is already outdated and not compatible with recent playwright >= 1.15

You would have to upgrade the code by refering the README of this repository.
